services:
  - type: web
    name: n8n-hackzero
    runtime: image
    image:
      url: docker.n8n.io/n8nio/n8n:latest
    env: production
    plan: free
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
    envVars:
      - key: PORT
        value: 5678
      - key: WEBHOOK_URL
        sync: false
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: n8n-postgres
          property: connectionString
      - key: DB_TYPE
        value: postgresdb

databases:
  - name: n8n-postgres
    databaseName: n8n
    plan: free
    ipAllowList: []
